/**
 * Per-lift perimeter generation.
 *
 * For every scaffold lift we take the union of the building's occupancy slices
 * over that lift's height band, extract the outer silhouette, push it outward
 * by the required clearance and finally divide it into bays.
 *
 * Using the UNION over the band (rather than the silhouette at a single height)
 * is deliberate: the scaffold for a lift must clear the widest part of the
 * building within that lift, otherwise a standard would pass through a
 * projecting cornice or the underside of a setback.
 */

import type { OccupancyRaster, ScaffoldConfiguration, ScaffoldLevel, Vec2 } from '../types';
import { silhouetteAt } from './buildingAnalyzer';
import {
  area as polyArea,
  convexHull,
  offsetPolygon,
  perimeter as polyPerimeter,
  resampleWithCorners,
  vertexNormals,
} from './polygon';

export interface LevelBand {
  index: number;
  yBottom: number;
  yTop: number;
}

/** Split the scaffolded height range into lifts. */
export function computeBands(config: ScaffoldConfiguration, buildingHeight: number): LevelBand[] {
  const base = Math.max(0, config.baseHeight);
  const fraction = Math.min(1, Math.max(0.05, config.heightFraction));
  const top = Math.max(base + config.verticalSpacing, buildingHeight * fraction + config.topExtension);
  const lift = Math.max(0.3, config.verticalSpacing);
  const count = Math.max(1, Math.ceil((top - base) / lift));
  const bands: LevelBand[] = [];
  for (let i = 0; i < count; i++) {
    const yBottom = base + i * lift;
    bands.push({ index: i, yBottom, yTop: Math.min(top, yBottom + lift) });
  }
  return bands;
}

export interface PerimeterOptions {
  /** Fallback silhouette used when a band contains no building material. */
  fallback?: Vec2[] | null;
}

/**
 * Build the node ring for every lift.
 *
 * The returned `nodes` are the INNERMOST row of standards; additional rows are
 * generated by the scaffold generator by stepping along `normals`, which
 * guarantees every row has the same node count and therefore clean transoms
 * and rectangular decks.
 */
export function generateLevels(
  raster: OccupancyRaster,
  config: ScaffoldConfiguration,
  buildingHeight: number,
  options: PerimeterOptions = {},
): { levels: ScaffoldLevel[]; warnings: string[] } {
  const bands = computeBands(config, buildingHeight);
  const warnings: string[] = [];
  const levels: ScaffoldLevel[] = [];

  // The voxel silhouette already sits up to one cell outside the true surface,
  // so we discount half a cell from the requested clearance.
  const clearance = Math.max(0.05, config.buildingOffset - raster.cell * 0.5);
  let lastGood: Vec2[] | null = options.fallback ?? null;

  for (const band of bands) {
    let outline = silhouetteAt(raster, band.yBottom, band.yTop);

    // Above the roof (a top-extension lift) or through a gap in the mesh there
    // may be nothing to trace — carry the last valid outline upward.
    if (!outline || outline.length < 3 || polyArea(outline) < raster.cell * raster.cell * 2) {
      outline = lastGood;
      if (!outline) continue;
    } else {
      // Guard against pathological contours (self-touching voxel diagonals):
      // if the traced loop is wildly non-convex compared to its hull, fall back
      // to the hull, which is always a valid scaffold-able ring.
      const hull = convexHull(outline);
      if (polyArea(hull) > polyArea(outline) * 3.5) {
        outline = hull;
        warnings.push(`Level ${band.index + 1}: irregular silhouette approximated by its hull.`);
      }
      lastGood = outline;
    }

    const offset = offsetPolygon(outline, clearance);
    const nodes = resampleWithCorners(offset, config.horizontalSpacing);
    if (nodes.length < 3) continue;

    levels.push({
      index: band.index,
      elevation: band.yTop,
      liftHeight: band.yTop - band.yBottom,
      nodes,
      normals: vertexNormals(nodes),
      perimeter: polyPerimeter(nodes),
    });
  }

  if (!levels.length) {
    warnings.push('Could not derive any scaffold perimeter from this model.');
  }
  return { levels, warnings };
}
